### ISSUE TITLE
A valid Gruntfile could not be found.

### ISSUE THREAD

**Issue by gh-badreddine** [overleaf/clsi#139]
I'm trying to install the CLSI on my personal pc running ubuntu and on a GCP VM but I always get this error: A valid Gruntfile could not be found.
sorry, this is the first time to use grunt !!
Thanks very much for your answer.

## Steps to Reproduce

1. git clone https://github.com/overleaf/clsi.git
2. npm install
3. grunt install

## Context
I'm trying to install the CLSI on my ubuntu desktop and GCP VM.

## Technical Info
A valid Gruntfile could not be found. Please see the getting started guide for
more information on how to configure grunt: http://gruntjs.com/getting-started

* Operating System and version: Ubuntu 18.04 on my PC / using google cloud VM

**Comment by ShaneKilkelly** [comment]
Hi! I think the `grunt install` instruction is now obsolete, as we removed Grunt a while ago.
If you skip that step, does the CLSI just work?

**Comment by gh-badreddine** [comment]
no, it doesn't. it works fine on docker but not if I use the readme instructions.
this is what I tried:

- git clone https://github.com/overleaf/clsi.git

- npm install

- npm start

**Comment by ShaneKilkelly** [comment]
Does it work if you run `node app.js` (after the `npm install`)? 

I think the Readme for this project is very out of date, and the bottom line of the Dockerfile shows how we actually start this application in production: https://github.com/overleaf/clsi/blob/master/Dockerfile#L23

**Comment by johnsks** [comment]
Hello,

This is what I have done to install CLSI on Ubuntu 18.04 LTS, 

```
curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
sudo apt-get install gcc g++ make
sudo apt-get install -y nodejs
sudo apt-get update && sudo apt-get install yarn
sudo apt autoremove
nodejs --version
npm --version
git clone https://github.com/overleaf/clsi.git
cd clsi
npm install
npm audit fix
npm start
```

The CLSI service starts OK.  

root@localhost:/tmp# netstat -tupln
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.1:3013          0.0.0.0:*               LISTEN      16606/node
tcp        0      0 127.0.0.1:3048          0.0.0.0:*               LISTEN      16606/node
tcp        0      0 127.0.0.1:3049          0.0.0.0:*               LISTEN

However, the CLSI service throws an error when I call it from CURL.  I will open up a separate ticket for it.

Hope this information is helpful.

-John

**Comment by ShaneKilkelly** [comment]
Excellent! I'm glad it's working now. We'll try to update the documentation soon.
