### ISSUE TITLE
Compiling on Overleaf, but using favorite Desktop IDE?

### ISSUE THREAD

**Issue by aminya** [overleaf/clsi#161]
Is it possible to send latex files to the Overleaf server and get the compiled PDF back? 

This is particularly useful when someone wants to use their favorite desktop IDE, but doesn't wanna install Latex locally.

**Comment by ShaneKilkelly** [comment]
Hi! While it would not be impossible for a user to write a script to send a compile request to the `overleaf.com` compile servers through their account, we don't offer a stable public API to accomplish the same. 

Perhaps another way to achieve the same effect, would be to set up the docker-based release of [Overleaf Community Edition](https://github.com/overleaf/overleaf/wiki/Quick-Start-Guide) locally, and use the desktop IDE to edit the files, while using the docker container to compile the PDF?

**Comment by jdleesmiller** [comment]
I should add that we do offer such a stable API for some of our commercial partners, but it is not something that we've seen a lot of demand for from end users so far, so we haven't made it available in that way (yet). If you would like more information about a potential partnership, please contact us via www.overleaf.com/contact .
