### ISSUE TITLE
how to invoke LaTeX with the -shell-escape flag

### ISSUE THREAD

**Issue by jnhu76** [overleaf/clsi#244]
I'm trying to compile this code, but I get an error. `! Package minted Error: You must invoke LaTeX with the -shell-escape flag.`

```
\documentclass{article}
\usepackage{minted}
\begin{document}
\begin{minted}{python}
print("hello world")
\end{minted}
\end{document}
```

How can I invoke `shell-escape` flag in CLSI

**Comment by das7pad** [comment]
Hi!

Thank you for taking the time to write up this issue.

We are in the process of migrating to a monorepo at https://github.com/overleaf/overleaf and will mark this repository read-only soon.
You can read more about the monorepo migration at https://github.com/overleaf/overleaf/issues/923.

We are going to close this issue now to avoid any confusion about the inability to comment further.

If you believe this issue still needs addressing, please create a new issue at https://github.com/overleaf/overleaf.

Thanks again!
