### ISSUE TITLE
sqllite3@2.2.7 install fails on node@0.12

### ISSUE THREAD

**Issue by wendelb** [overleaf/clsi#25]
Had to change to v3.0.8 (latest) to install on my machine with node v0.12

**Comment by RusAlex** [comment]
Having the same issue

```bash
Darwin mac 16.1.0 Darwin Kernel Version 16.1.0: 
node v7.2.1
npm v3.10.9
```

**Comment by das7pad** [comment]
Hi!

Thank you for taking the time to write up this issue.

We are in the process of migrating to a monorepo at https://github.com/overleaf/overleaf and will mark this repository read-only soon.
You can read more about the monorepo migration at https://github.com/overleaf/overleaf/issues/923.

We are going to close this issue now to avoid any confusion about the inability to comment further.

If you believe this issue still needs addressing, please create a new issue at https://github.com/overleaf/overleaf.

Thanks again!
