### ISSUE TITLE
sqlite error: "SQLITE_BUSY: database is locked"

### ISSUE THREAD

**Issue by ltronky** [overleaf/clsi#35]
Hi, great job with ShareLatex, it's a very interesting project.
In the last day I start experiencing an issue with the compiler module. Here's the the error stack: 
`[2016-02-04T17:21:34.331Z] ERROR: clsi/87485 on Mac.local: error downloading file for resources (project_id=566f5b422cd1e813de233c40, modified=2016-02-04T17:21:33.470Z)
    SequelizeTimeoutError: SQLITE_BUSY: database is locked
        at module.exports.Query.formatError (/Users/luca/lsharelatex/clsi/node_modules/sequelize/lib/dialects/sqlite/query.js:236:16)
        at Statement.<anonymous> (/Users/luca/lsharelatex/clsi/node_modules/sequelize/lib/dialects/sqlite/query.js:47:31)
        at Statement.replacement (/Users/luca/lsharelatex/clsi/node_modules/sqlite3/lib/trace.js:20:31)
    --
    path: /Users/luca/lsharelatex/data/compiles/566f5b422cd1e813de233c40/ce0test1m1fig1.png
    --
    resource_url: http://localhost:3009/project/566f5b422cd1e813de233c40/file/56b3889d70364cdb55f76abd`

Near a week ago it worked, and in that moment I also built a docker image that it is currently working. But now, I have this problem both: in my development environment and also in the docker builds that I made.

I haven't make any change on this component, so I think also you could be experiencing the same issue.

**Comment by ltronky** [comment]
I temporary fix the issue reverting the commit
https://github.com/sharelatex/clsi-sharelatex/commit/03b75b12cfad9b8d0ddfc16038e03a6cc33685ff
I think the problem is due to the slowliness of SQLite and a too little timeout.

**Comment by henryoswald** [comment]
Thanks, we will have a look at this. Maybe we will have to make that configurable. We use mysql in production for this which handles it without issue. Im surprised sql blows up in that manor.

**Comment by dpasqualin** [comment]
Hello @henryoswald,  I'm facing the same issue. is it possible to use mysql in the community edition too?

**Comment by henryoswald** [comment]
FILESTORE_PARALLEL_SQL_QUERY_LIMIT is now available to help fix this.
